const books = [
    {
      _id: '1',
      title: 'The Kite Runner',
      author: 'Khaled Hosseini',
      isbn: '9780385699426',
      category: 'Fiction',
      price: 39.99,
      description:
        'A powerful story of friendship, it is also about the power of reading, the price of betrayal and the possibility of redemption; and an exploration of the influence of fathers over sons—their love, their sacrifices, their lies',
      publisher: 'Berkley',
      publishedDate: '2021-09-17T00:00:00.000+00:00',
      stockQuantity: 10,
      coverImageUrl: '/images/kite-runner.jpg',
    },
    {
      _id: '2',
      title: 'Will',
      author: 'Will Smith with Mark Manson',
      isbn: '1984877925',
      category: 'Non-fiction',
      price: 39.99,
      description:
        'One of the most dynamic and globally recognized entertainment forces of our time opens up fully about his life, in a brave and inspiring book that traces his learning curve to a place where outer success, inner happiness, and human connection are aligned. Along the way, Will tells the story in full of one of the most amazing rides through the worlds of music and film that anyone has ever had.',
      publisher: 'Penguin Press',
      publishedDate: '2024-01-24T00:00:00.000+00:00',
      stockQuantity: 10,
      coverImageUrl: '/images/will.jpg',
    },
    {
      _id: '3',
      title: 'Berserk',
      author: 'Kentaro Miura',
      isbn: '9781506711980',
      category: 'Fiction',
      price: 54.98,
      description:
        'Have you got the Guts Kentaro Miuras Berserk has outraged, horrified, and delighted manga and anime fanatics since 1989, creating an international legion of hardcore devotees and inspiring a plethora of TV series, feature films, and video games. And now the badass champion of adult fantasy manga, nearly 700 pages amassing the first three Berserk volumes, with following volumes to come to serve up the entire series in handsome bookshelf collections. No Guts, no glory!',
      publisher: 'Dark Horse Manga',
      publishedDate: '2019-03-26T00:00:00.000+00:00',
      stockQuantity: 50,
      coverImageUrl: '/images/kite-runner.jpg',
    },
    {
      _id: '4',
      title: 'A Clash of Kings',
      author: 'George R. R. Martin',
      isbn: '9781984821157',
      category: 'Fiction',
      price: 39.99,
      description:
        'A stunning illustrated edition of the second book in the beloved A Song of Ice and Fire series, for fans of HBOs Game of Thrones',
      publisher: 'Bantam',
      publishedDate: '2019-11-05T00:00:00.000+00:00',
      stockQuantity: 10,
      coverImageUrl: '/images/clash.jpg',
    },
    {
      _id: '5',
      title: 'Is Everyone Hanging Out ...',
      author: 'Mindy Kaling',
      isbn: '0307886271',
      category: 'Fiction',
      price: 22.49,
      description:
        'Mindy Kaling has lived many lives: the obedient child of immigrant professionals, a timid chubster afraid of her own bike, a Ben Affleck–impersonating Off-Broadway performer and playwright, and, finally, a comedy writer and actress prone to starting fights with her friends and coworkers with the sentence “Can I just say one last thing about this, and then I swear I’ll shut up about it?”',
      publisher: 'Crown',
      publishedDate: '2012-09-17T00:00:00.000+00:00',
      stockQuantity: 10,
      coverImageUrl: '/images/mindy.jpg',
    },
    {
      _id: '6',
      title: 'Chocolate All Day',
      author: 'Steven Hodge',
      isbn: '9780525612025',
      category: 'Cookbook',
      price: 37.50,
      description:
        'Calling all chocolate lovers! Its the bake book youve been waiting for, with over 100 rich, delicious, yet accessible recipes for baking with chocolate all day long.',
      publisher: 'Appetite by Random House',
      publishedDate: '2023-10-17T00:00:00.000+00:00',
      stockQuantity: 10,
      coverImageUrl: '/images/chocolate.jpg',
    },
  ]
  
  export default books